# Generated by Django 5.2.6 on 2025-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
