# Generated by Django 5.2.6 on 2025-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_dispositivo_data_aquisicao_dispositivo_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='mascara_rede',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
