# Generated by Django 5.2.6 on 2025-09-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_dispositivo_gateway_dispositivo_mascara_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_conexao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('caminho', models.TextField()),
                ('tamanho', models.BigIntegerField(help_text='Tamanho em bytes')),
                ('tipo_arquivo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('perdida', 'Perdida')], max_length=10)),
                ('duracao', models.IntegerField(help_text='Duração em segundos')),
                ('data_chamada', models.DateTimeField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], max_length=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pacote', models.CharField(max_length=200)),
                ('versao', models.CharField(blank=True, max_length=50)),
                ('data_instalacao', models.DateTimeField(blank=True, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicativos', to='monitoramento.dispositivo')),
            ],
            options={
                'unique_together': {('dispositivo', 'pacote')},
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='monitoramento.dispositivo')),
            ],
            options={
                'unique_together': {('dispositivo', 'telefone')},
            },
        ),
    ]
