# Generated by Django 5.2.6 on 2025-10-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_dispositivo_ultima_conexao_arquivo_chamada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_local', models.GenericIPAddressField()),
                ('ip_publico', models.GenericIPAddressField(blank=True, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100)),
                ('wifi_status', models.CharField(blank=True, max_length=50)),
                ('velocidade_download', models.FloatField(blank=True, null=True)),
                ('velocidade_upload', models.FloatField(blank=True, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_rede', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_midia', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo'), ('audio', 'Áudio')], max_length=20)),
                ('tamanho', models.BigIntegerField(help_text='Tamanho em bytes')),
                ('arquivo', models.FileField(upload_to='midias/%Y/%m/%d/')),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('localização', models.CharField(blank=True, max_length=500)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='monitoramento.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(max_length=100)),
                ('pacote', models.CharField(max_length=200)),
                ('instalado', models.BooleanField(default=True)),
                ('ultima_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='monitoramento.dispositivo')),
            ],
            options={
                'unique_together': {('dispositivo', 'pacote')},
            },
        ),
    ]
