# Generated by Django 5.2.5 on 2025-11-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_atividaderede_midia_redesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='armazenamento_livre',
            field=models.BigIntegerField(blank=True, help_text='Armazenamento livre em bytes', null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='armazenamento_total',
            field=models.BigIntegerField(blank=True, help_text='Armazenamento total em bytes', null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='armazenamento_usado',
            field=models.BigIntegerField(blank=True, help_text='Armazenamento usado em bytes', null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='bateria_carregando',
            field=models.BooleanField(default=False, help_text='Se a bateria está carregando'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='bateria_nivel',
            field=models.IntegerField(blank=True, help_text='Nível da bateria em porcentagem', null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='bateria_temperatura',
            field=models.FloatField(blank=True, help_text='Temperatura da bateria em Celsius', null=True),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['imei'], name='monitoramen_imei_aace82_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['ip'], name='monitoramen_ip_b064b9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['status'], name='monitoramen_status_420a17_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['ultima_conexao'], name='monitoramen_ultima__b05e20_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['usuario'], name='monitoramen_usuario_b154bb_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['departamento'], name='monitoramen_departa_4f8a3f_idx'),
        ),
    ]
